version: '3'
services:
        back:
                build:
                        context: ./back
                        dockerfile: Dockerfile
                ports: 
                        - '3000:3000'
                env_file: 
                        - ./back/.env
                volumes:
                        - ${PWD}/back/weatherDB:/app/weatherDB
                restart: always
        front:
                build:
                        context: ./front
                        dockerfile: Dockerfile
                ports:
                        - '8080:8081'
                depends_on:
                        - back
                env_file:
                        - ./front/.env
                restart: always


volumes:
        db:
                driver: local
                driver_opts:
                        type: none
                        device: ${PWD}/back/weatherDB
                        o: bind
