import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {useEffect, useState} from "react";
import axios from "axios";
import {console} from "next/dist/compiled/@edge-runtime/primitives/console";
import {getCookie, removeCookies} from "cookies-next";

export function MyHead({title}) {
    return (
        <Head>
            <title>{title + ' - Weather App'}</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/icons/abugida-devanagari.png"/>
        </Head>
    )
}

function MyTitle() {
    return ( <div className={styles.title}>
            <h1>Weather App</h1>
            <p>by <a href={"https://github.com/ericard42"}>ericard</a></p>
        </div>
    )
}

function Connexion() {
    return (
        <div className={styles.login_box}>
            <Link href={"/login"}>
                <a className={styles.text}>
                    Login
                </a>
            </Link>
            {" or "}
            <Link href={"/inscription"}>
                <a className={styles.text}>
                    Inscription
                </a>
            </Link>
        </div>
    )
}

function Welcome({username}) {
    return (
        <h1>Welcome {username} !</h1>
    )
}

function Favorites() {
    return (
        <></>
    )
}

function CurrentLocation() {
    return (
        <></>
    )
}

function Search() {
    return (
        <div className={styles.search_box}>
            <h3>Search Location :</h3>
            <input type={"text"} name={"location"}></input>
        </div>
    )
}

export default function Home() {
    const [name, setName] = useState("")
    let username = ""
    let token = ""

    const checkUser = async () => {
        axios({
            method: 'get',
            url: "http://localhost:3000/user/" + name,
            headers: {
                Authorization: 'Bearer ' + token,
                "content-type": "application/json",
            }
        })
            .then((response) => {
                return true
            })
            .catch((e) => {
                return false
            })
    }

    useEffect(  () => {
        window.localStorage.setItem("session", 'nfesdecjnmeas')
        window.localStorage.setItem('username', "ericard")

        token = window.localStorage.getItem("session")
        username = window.localStorage.getItem("username")

        console.log(token)
        console.log(username)
        if (!token || !username) {
            console.log("Not Logged in")
        }
        else {
            (async () => {
                console.log("Logged In")
                if (await checkUser() === true) {
                    console.log("Verification is good")
                    setName(username)
                }
                else {
                    console.log("Verification is bad")
                    throw 'User not found'
                }
            })()
                .catch((e) => {
                    throw e
                })
        }
        return () => {}
    }, [])

  return (
    <div className={styles.container}>
      <MyHead title={'Home'}/>

      <main className={styles.main}>
        <MyTitle/>
          <div className={styles.content}>
              { name !== "" ? <Welcome username={name}/> : <Connexion/> }
              <Search/>
          </div>
      </main>

    </div>
  )
}
